// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpErr is an autogenerated mock type for the HttpErr type
type HttpErr struct {
	mock.Mock
}

// Details provides a mock function with given fields:
func (_m *HttpErr) Details() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *HttpErr) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *HttpErr) Status() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewHttpErr interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpErr creates a new instance of HttpErr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpErr(t mockConstructorTestingTNewHttpErr) *HttpErr {
	mock := &HttpErr{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
